// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

package ch.rasc.dataformat.proto;

public final class AddressProtos {
  private AddressProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string lastName = 2;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 2;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string firstName = 3;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 3;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string street = 4;</code>
     * @return The street.
     */
    java.lang.String getStreet();
    /**
     * <code>string street = 4;</code>
     * @return The bytes for street.
     */
    com.google.protobuf.ByteString
        getStreetBytes();

    /**
     * <code>string zip = 5;</code>
     * @return The zip.
     */
    java.lang.String getZip();
    /**
     * <code>string zip = 5;</code>
     * @return The bytes for zip.
     */
    com.google.protobuf.ByteString
        getZipBytes();

    /**
     * <code>string city = 6;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 6;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string country = 7;</code>
     * @return The country.
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 7;</code>
     * @return The bytes for country.
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>float lat = 8;</code>
     * @return The lat.
     */
    float getLat();

    /**
     * <code>float lng = 9;</code>
     * @return The lng.
     */
    float getLng();

    /**
     * <code>string email = 10;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 10;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>sint32 dob = 11;</code>
     * @return The dob.
     */
    int getDob();
  }
  /**
   * Protobuf type {@code Address}
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      lastName_ = "";
      firstName_ = "";
      street_ = "";
      zip_ = "";
      city_ = "";
      country_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.rasc.dataformat.proto.AddressProtos.internal_static_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.rasc.dataformat.proto.AddressProtos.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.rasc.dataformat.proto.AddressProtos.Address.class, ch.rasc.dataformat.proto.AddressProtos.Address.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastName_ = "";
    /**
     * <code>string lastName = 2;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 2;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object firstName_ = "";
    /**
     * <code>string firstName = 3;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 3;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STREET_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object street_ = "";
    /**
     * <code>string street = 4;</code>
     * @return The street.
     */
    @java.lang.Override
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      }
    }
    /**
     * <code>string street = 4;</code>
     * @return The bytes for street.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIP_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object zip_ = "";
    /**
     * <code>string zip = 5;</code>
     * @return The zip.
     */
    @java.lang.Override
    public java.lang.String getZip() {
      java.lang.Object ref = zip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zip_ = s;
        return s;
      }
    }
    /**
     * <code>string zip = 5;</code>
     * @return The bytes for zip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getZipBytes() {
      java.lang.Object ref = zip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <code>string city = 6;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 6;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object country_ = "";
    /**
     * <code>string country = 7;</code>
     * @return The country.
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string country = 7;</code>
     * @return The bytes for country.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAT_FIELD_NUMBER = 8;
    private float lat_ = 0F;
    /**
     * <code>float lat = 8;</code>
     * @return The lat.
     */
    @java.lang.Override
    public float getLat() {
      return lat_;
    }

    public static final int LNG_FIELD_NUMBER = 9;
    private float lng_ = 0F;
    /**
     * <code>float lng = 9;</code>
     * @return The lng.
     */
    @java.lang.Override
    public float getLng() {
      return lng_;
    }

    public static final int EMAIL_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 10;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 10;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOB_FIELD_NUMBER = 11;
    private int dob_ = 0;
    /**
     * <code>sint32 dob = 11;</code>
     * @return The dob.
     */
    @java.lang.Override
    public int getDob() {
      return dob_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, street_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(zip_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, zip_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, city_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(country_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, country_);
      }
      if (java.lang.Float.floatToRawIntBits(lat_) != 0) {
        output.writeFloat(8, lat_);
      }
      if (java.lang.Float.floatToRawIntBits(lng_) != 0) {
        output.writeFloat(9, lng_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, email_);
      }
      if (dob_ != 0) {
        output.writeSInt32(11, dob_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, street_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(zip_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, zip_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, city_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(country_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, country_);
      }
      if (java.lang.Float.floatToRawIntBits(lat_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, lat_);
      }
      if (java.lang.Float.floatToRawIntBits(lng_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, lng_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, email_);
      }
      if (dob_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(11, dob_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.rasc.dataformat.proto.AddressProtos.Address)) {
        return super.equals(obj);
      }
      ch.rasc.dataformat.proto.AddressProtos.Address other = (ch.rasc.dataformat.proto.AddressProtos.Address) obj;

      if (getId()
          != other.getId()) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getStreet()
          .equals(other.getStreet())) return false;
      if (!getZip()
          .equals(other.getZip())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getCountry()
          .equals(other.getCountry())) return false;
      if (java.lang.Float.floatToIntBits(getLat())
          != java.lang.Float.floatToIntBits(
              other.getLat())) return false;
      if (java.lang.Float.floatToIntBits(getLng())
          != java.lang.Float.floatToIntBits(
              other.getLng())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (getDob()
          != other.getDob()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + STREET_FIELD_NUMBER;
      hash = (53 * hash) + getStreet().hashCode();
      hash = (37 * hash) + ZIP_FIELD_NUMBER;
      hash = (53 * hash) + getZip().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLat());
      hash = (37 * hash) + LNG_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLng());
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + DOB_FIELD_NUMBER;
      hash = (53 * hash) + getDob();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ch.rasc.dataformat.proto.AddressProtos.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ch.rasc.dataformat.proto.AddressProtos.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.rasc.dataformat.proto.AddressProtos.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.rasc.dataformat.proto.AddressProtos.internal_static_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.rasc.dataformat.proto.AddressProtos.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.rasc.dataformat.proto.AddressProtos.Address.class, ch.rasc.dataformat.proto.AddressProtos.Address.Builder.class);
      }

      // Construct using ch.rasc.dataformat.proto.AddressProtos.Address.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        lastName_ = "";
        firstName_ = "";
        street_ = "";
        zip_ = "";
        city_ = "";
        country_ = "";
        lat_ = 0F;
        lng_ = 0F;
        email_ = "";
        dob_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.rasc.dataformat.proto.AddressProtos.internal_static_Address_descriptor;
      }

      @java.lang.Override
      public ch.rasc.dataformat.proto.AddressProtos.Address getDefaultInstanceForType() {
        return ch.rasc.dataformat.proto.AddressProtos.Address.getDefaultInstance();
      }

      @java.lang.Override
      public ch.rasc.dataformat.proto.AddressProtos.Address build() {
        ch.rasc.dataformat.proto.AddressProtos.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.rasc.dataformat.proto.AddressProtos.Address buildPartial() {
        ch.rasc.dataformat.proto.AddressProtos.Address result = new ch.rasc.dataformat.proto.AddressProtos.Address(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ch.rasc.dataformat.proto.AddressProtos.Address result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.lastName_ = lastName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.firstName_ = firstName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.street_ = street_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.zip_ = zip_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.country_ = country_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.lat_ = lat_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.lng_ = lng_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.dob_ = dob_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.rasc.dataformat.proto.AddressProtos.Address) {
          return mergeFrom((ch.rasc.dataformat.proto.AddressProtos.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.rasc.dataformat.proto.AddressProtos.Address other) {
        if (other == ch.rasc.dataformat.proto.AddressProtos.Address.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getStreet().isEmpty()) {
          street_ = other.street_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getZip().isEmpty()) {
          zip_ = other.zip_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getLat() != 0F) {
          setLat(other.getLat());
        }
        if (other.getLng() != 0F) {
          setLng(other.getLng());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (other.getDob() != 0) {
          setDob(other.getDob());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                lastName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                firstName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                street_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                zip_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                country_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 69: {
                lat_ = input.readFloat();
                bitField0_ |= 0x00000080;
                break;
              } // case 69
              case 77: {
                lng_ = input.readFloat();
                bitField0_ |= 0x00000100;
                break;
              } // case 77
              case 82: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 88: {
                dob_ = input.readSInt32();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 2;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        lastName_ = getDefaultInstance().getLastName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 3;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 3;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 3;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        firstName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        firstName_ = getDefaultInstance().getFirstName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 3;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        firstName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object street_ = "";
      /**
       * <code>string street = 4;</code>
       * @return The street.
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          street_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string street = 4;</code>
       * @return The bytes for street.
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string street = 4;</code>
       * @param value The street to set.
       * @return This builder for chaining.
       */
      public Builder setStreet(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        street_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string street = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreet() {
        street_ = getDefaultInstance().getStreet();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string street = 4;</code>
       * @param value The bytes for street to set.
       * @return This builder for chaining.
       */
      public Builder setStreetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        street_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object zip_ = "";
      /**
       * <code>string zip = 5;</code>
       * @return The zip.
       */
      public java.lang.String getZip() {
        java.lang.Object ref = zip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string zip = 5;</code>
       * @return The bytes for zip.
       */
      public com.google.protobuf.ByteString
          getZipBytes() {
        java.lang.Object ref = zip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string zip = 5;</code>
       * @param value The zip to set.
       * @return This builder for chaining.
       */
      public Builder setZip(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        zip_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string zip = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearZip() {
        zip_ = getDefaultInstance().getZip();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string zip = 5;</code>
       * @param value The bytes for zip to set.
       * @return This builder for chaining.
       */
      public Builder setZipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        zip_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 6;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 6;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 6;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 6;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string country = 7;</code>
       * @return The country.
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country = 7;</code>
       * @return The bytes for country.
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country = 7;</code>
       * @param value The country to set.
       * @return This builder for chaining.
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        country_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string country = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountry() {
        country_ = getDefaultInstance().getCountry();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string country = 7;</code>
       * @param value The bytes for country to set.
       * @return This builder for chaining.
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        country_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private float lat_ ;
      /**
       * <code>float lat = 8;</code>
       * @return The lat.
       */
      @java.lang.Override
      public float getLat() {
        return lat_;
      }
      /**
       * <code>float lat = 8;</code>
       * @param value The lat to set.
       * @return This builder for chaining.
       */
      public Builder setLat(float value) {

        lat_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>float lat = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000080);
        lat_ = 0F;
        onChanged();
        return this;
      }

      private float lng_ ;
      /**
       * <code>float lng = 9;</code>
       * @return The lng.
       */
      @java.lang.Override
      public float getLng() {
        return lng_;
      }
      /**
       * <code>float lng = 9;</code>
       * @param value The lng to set.
       * @return This builder for chaining.
       */
      public Builder setLng(float value) {

        lng_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>float lng = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLng() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lng_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 10;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 10;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 10;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 10;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private int dob_ ;
      /**
       * <code>sint32 dob = 11;</code>
       * @return The dob.
       */
      @java.lang.Override
      public int getDob() {
        return dob_;
      }
      /**
       * <code>sint32 dob = 11;</code>
       * @param value The dob to set.
       * @return This builder for chaining.
       */
      public Builder setDob(int value) {

        dob_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 dob = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearDob() {
        bitField0_ = (bitField0_ & ~0x00000400);
        dob_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final ch.rasc.dataformat.proto.AddressProtos.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.rasc.dataformat.proto.AddressProtos.Address();
    }

    public static ch.rasc.dataformat.proto.AddressProtos.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.rasc.dataformat.proto.AddressProtos.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Addresses)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Address address = 1;</code>
     */
    java.util.List<ch.rasc.dataformat.proto.AddressProtos.Address> 
        getAddressList();
    /**
     * <code>repeated .Address address = 1;</code>
     */
    ch.rasc.dataformat.proto.AddressProtos.Address getAddress(int index);
    /**
     * <code>repeated .Address address = 1;</code>
     */
    int getAddressCount();
    /**
     * <code>repeated .Address address = 1;</code>
     */
    java.util.List<? extends ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder> 
        getAddressOrBuilderList();
    /**
     * <code>repeated .Address address = 1;</code>
     */
    ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder getAddressOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Addresses}
   */
  public static final class Addresses extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Addresses)
      AddressesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Addresses.newBuilder() to construct.
    private Addresses(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Addresses() {
      address_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Addresses();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.rasc.dataformat.proto.AddressProtos.internal_static_Addresses_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.rasc.dataformat.proto.AddressProtos.internal_static_Addresses_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.rasc.dataformat.proto.AddressProtos.Addresses.class, ch.rasc.dataformat.proto.AddressProtos.Addresses.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<ch.rasc.dataformat.proto.AddressProtos.Address> address_;
    /**
     * <code>repeated .Address address = 1;</code>
     */
    @java.lang.Override
    public java.util.List<ch.rasc.dataformat.proto.AddressProtos.Address> getAddressList() {
      return address_;
    }
    /**
     * <code>repeated .Address address = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder> 
        getAddressOrBuilderList() {
      return address_;
    }
    /**
     * <code>repeated .Address address = 1;</code>
     */
    @java.lang.Override
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated .Address address = 1;</code>
     */
    @java.lang.Override
    public ch.rasc.dataformat.proto.AddressProtos.Address getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated .Address address = 1;</code>
     */
    @java.lang.Override
    public ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder getAddressOrBuilder(
        int index) {
      return address_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < address_.size(); i++) {
        output.writeMessage(1, address_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < address_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, address_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.rasc.dataformat.proto.AddressProtos.Addresses)) {
        return super.equals(obj);
      }
      ch.rasc.dataformat.proto.AddressProtos.Addresses other = (ch.rasc.dataformat.proto.AddressProtos.Addresses) obj;

      if (!getAddressList()
          .equals(other.getAddressList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAddressCount() > 0) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddressList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.rasc.dataformat.proto.AddressProtos.Addresses parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.rasc.dataformat.proto.AddressProtos.Addresses prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Addresses}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Addresses)
        ch.rasc.dataformat.proto.AddressProtos.AddressesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.rasc.dataformat.proto.AddressProtos.internal_static_Addresses_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.rasc.dataformat.proto.AddressProtos.internal_static_Addresses_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.rasc.dataformat.proto.AddressProtos.Addresses.class, ch.rasc.dataformat.proto.AddressProtos.Addresses.Builder.class);
      }

      // Construct using ch.rasc.dataformat.proto.AddressProtos.Addresses.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
        } else {
          address_ = null;
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.rasc.dataformat.proto.AddressProtos.internal_static_Addresses_descriptor;
      }

      @java.lang.Override
      public ch.rasc.dataformat.proto.AddressProtos.Addresses getDefaultInstanceForType() {
        return ch.rasc.dataformat.proto.AddressProtos.Addresses.getDefaultInstance();
      }

      @java.lang.Override
      public ch.rasc.dataformat.proto.AddressProtos.Addresses build() {
        ch.rasc.dataformat.proto.AddressProtos.Addresses result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.rasc.dataformat.proto.AddressProtos.Addresses buildPartial() {
        ch.rasc.dataformat.proto.AddressProtos.Addresses result = new ch.rasc.dataformat.proto.AddressProtos.Addresses(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ch.rasc.dataformat.proto.AddressProtos.Addresses result) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            address_ = java.util.Collections.unmodifiableList(address_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
      }

      private void buildPartial0(ch.rasc.dataformat.proto.AddressProtos.Addresses result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.rasc.dataformat.proto.AddressProtos.Addresses) {
          return mergeFrom((ch.rasc.dataformat.proto.AddressProtos.Addresses)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.rasc.dataformat.proto.AddressProtos.Addresses other) {
        if (other == ch.rasc.dataformat.proto.AddressProtos.Addresses.getDefaultInstance()) return this;
        if (addressBuilder_ == null) {
          if (!other.address_.isEmpty()) {
            if (address_.isEmpty()) {
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAddressIsMutable();
              address_.addAll(other.address_);
            }
            onChanged();
          }
        } else {
          if (!other.address_.isEmpty()) {
            if (addressBuilder_.isEmpty()) {
              addressBuilder_.dispose();
              addressBuilder_ = null;
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000001);
              addressBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddressFieldBuilder() : null;
            } else {
              addressBuilder_.addAllMessages(other.address_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                ch.rasc.dataformat.proto.AddressProtos.Address m =
                    input.readMessage(
                        ch.rasc.dataformat.proto.AddressProtos.Address.parser(),
                        extensionRegistry);
                if (addressBuilder_ == null) {
                  ensureAddressIsMutable();
                  address_.add(m);
                } else {
                  addressBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<ch.rasc.dataformat.proto.AddressProtos.Address> address_ =
        java.util.Collections.emptyList();
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          address_ = new java.util.ArrayList<ch.rasc.dataformat.proto.AddressProtos.Address>(address_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ch.rasc.dataformat.proto.AddressProtos.Address, ch.rasc.dataformat.proto.AddressProtos.Address.Builder, ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder> addressBuilder_;

      /**
       * <code>repeated .Address address = 1;</code>
       */
      public java.util.List<ch.rasc.dataformat.proto.AddressProtos.Address> getAddressList() {
        if (addressBuilder_ == null) {
          return java.util.Collections.unmodifiableList(address_);
        } else {
          return addressBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public int getAddressCount() {
        if (addressBuilder_ == null) {
          return address_.size();
        } else {
          return addressBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public ch.rasc.dataformat.proto.AddressProtos.Address getAddress(int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);
        } else {
          return addressBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder setAddress(
          int index, ch.rasc.dataformat.proto.AddressProtos.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.set(index, value);
          onChanged();
        } else {
          addressBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder setAddress(
          int index, ch.rasc.dataformat.proto.AddressProtos.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAddress(ch.rasc.dataformat.proto.AddressProtos.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(value);
          onChanged();
        } else {
          addressBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAddress(
          int index, ch.rasc.dataformat.proto.AddressProtos.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(index, value);
          onChanged();
        } else {
          addressBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAddress(
          ch.rasc.dataformat.proto.AddressProtos.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAddress(
          int index, ch.rasc.dataformat.proto.AddressProtos.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAllAddress(
          java.lang.Iterable<? extends ch.rasc.dataformat.proto.AddressProtos.Address> values) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, address_);
          onChanged();
        } else {
          addressBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder removeAddress(int index) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.remove(index);
          onChanged();
        } else {
          addressBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public ch.rasc.dataformat.proto.AddressProtos.Address.Builder getAddressBuilder(
          int index) {
        return getAddressFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder getAddressOrBuilder(
          int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);  } else {
          return addressBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public java.util.List<? extends ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder> 
           getAddressOrBuilderList() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(address_);
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public ch.rasc.dataformat.proto.AddressProtos.Address.Builder addAddressBuilder() {
        return getAddressFieldBuilder().addBuilder(
            ch.rasc.dataformat.proto.AddressProtos.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public ch.rasc.dataformat.proto.AddressProtos.Address.Builder addAddressBuilder(
          int index) {
        return getAddressFieldBuilder().addBuilder(
            index, ch.rasc.dataformat.proto.AddressProtos.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public java.util.List<ch.rasc.dataformat.proto.AddressProtos.Address.Builder> 
           getAddressBuilderList() {
        return getAddressFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ch.rasc.dataformat.proto.AddressProtos.Address, ch.rasc.dataformat.proto.AddressProtos.Address.Builder, ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ch.rasc.dataformat.proto.AddressProtos.Address, ch.rasc.dataformat.proto.AddressProtos.Address.Builder, ch.rasc.dataformat.proto.AddressProtos.AddressOrBuilder>(
                  address_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Addresses)
    }

    // @@protoc_insertion_point(class_scope:Addresses)
    private static final ch.rasc.dataformat.proto.AddressProtos.Addresses DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.rasc.dataformat.proto.AddressProtos.Addresses();
    }

    public static ch.rasc.dataformat.proto.AddressProtos.Addresses getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Addresses>
        PARSER = new com.google.protobuf.AbstractParser<Addresses>() {
      @java.lang.Override
      public Addresses parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Addresses> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Addresses> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.rasc.dataformat.proto.AddressProtos.Addresses getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Addresses_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Addresses_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raddress.proto\"\254\001\n\007Address\022\n\n\002id\030\001 \001(\r\022" +
      "\020\n\010lastName\030\002 \001(\t\022\021\n\tfirstName\030\003 \001(\t\022\016\n\006" +
      "street\030\004 \001(\t\022\013\n\003zip\030\005 \001(\t\022\014\n\004city\030\006 \001(\t\022" +
      "\017\n\007country\030\007 \001(\t\022\013\n\003lat\030\010 \001(\002\022\013\n\003lng\030\t \001" +
      "(\002\022\r\n\005email\030\n \001(\t\022\013\n\003dob\030\013 \001(\021\"&\n\tAddres" +
      "ses\022\031\n\007address\030\001 \003(\0132\010.AddressB)\n\030ch.ras" +
      "c.dataformat.protoB\rAddressProtosb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Id", "LastName", "FirstName", "Street", "Zip", "City", "Country", "Lat", "Lng", "Email", "Dob", });
    internal_static_Addresses_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Addresses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Addresses_descriptor,
        new java.lang.String[] { "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
